export const DEFAULT_CATEGORIES = [
  { id: 'food', name: 'Khana-Peena', icon: '🍛', color: '#F97316', type: 'expense' },
  { id: 'transport', name: 'Safar', icon: '🚗', color: '#3B82F6', type: 'expense' },
  { id: 'housing', name: 'Ghar', icon: '🏠', color: '#8B5CF6', type: 'expense' },
  { id: 'health', name: 'Sehat', icon: '💊', color: '#EF4444', type: 'expense' },
  { id: 'education', name: 'Padhai', icon: '📚', color: '#10B981', type: 'expense' },
  { id: 'shopping', name: 'Shopping', icon: '🛍️', color: '#EC4899', type: 'expense' },
  { id: 'bills', name: 'Bills & Utilities', icon: '⚡', color: '#F59E0B', type: 'expense' },
  { id: 'mobile', name: 'Mobile & Net', icon: '📱', color: '#14B8A6', type: 'expense' },
  { id: 'entertainment', name: 'Manoranjan', icon: '🎬', color: '#6366F1', type: 'expense' },
  { id: 'investment', name: 'Nivesh', icon: '📈', color: '#059669', type: 'expense' },
  { id: 'salary', name: 'Salary', icon: '💰', color: '#22C55E', type: 'income' },
  { id: 'freelance', name: 'Freelance', icon: '💻', color: '#06B6D4', type: 'income' },
  { id: 'other', name: 'Anya', icon: '📦', color: '#94A3B8', type: 'expense' },
]

export const DEFAULT_TAGS = [
  { id: 'zaruri', name: 'zaruri', color: '#EF4444' },
  { id: 'fixed', name: 'fixed', color: '#3B82F6' },
  { id: 'luxury', name: 'luxury', color: '#8B5CF6' },
  { id: 'emi', name: 'emi', color: '#F59E0B' },
  { id: 'work', name: 'work', color: '#10B981' },
]

export const CATEGORY_COLORS = [
  '#F97316', '#EF4444', '#EC4899', '#8B5CF6', '#6366F1',
  '#3B82F6', '#06B6D4', '#14B8A6', '#10B981', '#22C55E',
  '#84CC16', '#F59E0B', '#D97706', '#059669', '#0891B2',
  '#7C3AED', '#DB2777', '#DC2626', '#94A3B8', '#64748B',
]

export const FREQUENCIES = ['daily', 'weekly', 'monthly', 'yearly']

export const EMOJI_LIST = [
  '🍛', '🍕', '🚗', '🏠', '💊', '📚', '🛍️', '⚡', '📱', '🎬',
  '📈', '💰', '💻', '📦', '✈️', '🏥', '🎓', '🎮', '🍔', '☕',
  '🚌', '🚇', '⛽', '🏋️', '💇', '🎁', '🎉', '🏖️', '🌴', '🎵',
  '🎨', '📸', '🐶', '🐱', '🌱', '🧴', '👕', '👟', '💍', '🏦',
  '💳', '🎯', '🧘', '🚴', '🏊', '🍺', '🍷', '🛒', '📰', '💡',
]

// Sample transactions for first load
const now = new Date()
const thisMonth = now.getMonth()
const thisYear = now.getFullYear()
const lastMonth = thisMonth === 0 ? 11 : thisMonth - 1
const lastMonthYear = thisMonth === 0 ? thisYear - 1 : thisYear

export const SAMPLE_TRANSACTIONS = [
  // This month transactions
  {
    id: 'txn_001',
    type: 'income',
    amount: 85000,
    categoryId: 'salary',
    note: 'March Salary - TCS Ltd',
    date: new Date(thisYear, thisMonth, 1).toISOString(),
    tags: ['fixed'],
    createdAt: new Date(thisYear, thisMonth, 1).toISOString(),
  },
  {
    id: 'txn_002',
    type: 'expense',
    amount: 18500,
    categoryId: 'housing',
    note: 'House Rent - March',
    date: new Date(thisYear, thisMonth, 2).toISOString(),
    tags: ['fixed', 'zaruri'],
    createdAt: new Date(thisYear, thisMonth, 2).toISOString(),
  },
  {
    id: 'txn_003',
    type: 'expense',
    amount: 3200,
    categoryId: 'food',
    note: 'Grocery from DMart',
    date: new Date(thisYear, thisMonth, 3).toISOString(),
    tags: ['zaruri'],
    createdAt: new Date(thisYear, thisMonth, 3).toISOString(),
  },
  {
    id: 'txn_004',
    type: 'expense',
    amount: 1499,
    categoryId: 'bills',
    note: 'BSES Electricity Bill',
    date: new Date(thisYear, thisMonth, 5).toISOString(),
    tags: ['fixed', 'zaruri'],
    createdAt: new Date(thisYear, thisMonth, 5).toISOString(),
  },
  {
    id: 'txn_005',
    type: 'income',
    amount: 22000,
    categoryId: 'freelance',
    note: 'Website project - ABC Corp',
    date: new Date(thisYear, thisMonth, 7).toISOString(),
    tags: ['work'],
    createdAt: new Date(thisYear, thisMonth, 7).toISOString(),
  },
  {
    id: 'txn_006',
    type: 'expense',
    amount: 4500,
    categoryId: 'shopping',
    note: 'Myntra - Clothes',
    date: new Date(thisYear, thisMonth, 8).toISOString(),
    tags: ['luxury'],
    createdAt: new Date(thisYear, thisMonth, 8).toISOString(),
  },
  {
    id: 'txn_007',
    type: 'expense',
    amount: 899,
    categoryId: 'mobile',
    note: 'Airtel Postpaid Bill',
    date: new Date(thisYear, thisMonth, 9).toISOString(),
    tags: ['fixed'],
    createdAt: new Date(thisYear, thisMonth, 9).toISOString(),
  },
  {
    id: 'txn_008',
    type: 'expense',
    amount: 2100,
    categoryId: 'transport',
    note: 'Petrol + Ola Cabs',
    date: new Date(thisYear, thisMonth, 10).toISOString(),
    tags: ['zaruri'],
    createdAt: new Date(thisYear, thisMonth, 10).toISOString(),
  },
  {
    id: 'txn_009',
    type: 'expense',
    amount: 1200,
    categoryId: 'entertainment',
    note: 'Netflix + Hotstar subscription',
    date: new Date(thisYear, thisMonth, 11).toISOString(),
    tags: ['luxury'],
    createdAt: new Date(thisYear, thisMonth, 11).toISOString(),
  },
  {
    id: 'txn_010',
    type: 'expense',
    amount: 15000,
    categoryId: 'investment',
    note: 'SIP - Zerodha Mutual Fund',
    date: new Date(thisYear, thisMonth, 12).toISOString(),
    tags: ['fixed'],
    createdAt: new Date(thisYear, thisMonth, 12).toISOString(),
  },
  {
    id: 'txn_011',
    type: 'expense',
    amount: 850,
    categoryId: 'food',
    note: 'Swiggy orders this week',
    date: new Date(thisYear, thisMonth, 14).toISOString(),
    tags: ['luxury'],
    createdAt: new Date(thisYear, thisMonth, 14).toISOString(),
  },
  {
    id: 'txn_012',
    type: 'expense',
    amount: 3500,
    categoryId: 'health',
    note: 'Apollo Pharmacy - medicines',
    date: new Date(thisYear, thisMonth, 15).toISOString(),
    tags: ['zaruri'],
    createdAt: new Date(thisYear, thisMonth, 15).toISOString(),
  },
  // Last month transactions
  {
    id: 'txn_013',
    type: 'income',
    amount: 85000,
    categoryId: 'salary',
    note: 'February Salary - TCS Ltd',
    date: new Date(lastMonthYear, lastMonth, 1).toISOString(),
    tags: ['fixed'],
    createdAt: new Date(lastMonthYear, lastMonth, 1).toISOString(),
  },
  {
    id: 'txn_014',
    type: 'expense',
    amount: 18500,
    categoryId: 'housing',
    note: 'House Rent - February',
    date: new Date(lastMonthYear, lastMonth, 2).toISOString(),
    tags: ['fixed', 'zaruri'],
    createdAt: new Date(lastMonthYear, lastMonth, 2).toISOString(),
  },
  {
    id: 'txn_015',
    type: 'expense',
    amount: 5800,
    categoryId: 'food',
    note: 'Grocery + Zomato + Cafe',
    date: new Date(lastMonthYear, lastMonth, 5).toISOString(),
    tags: ['zaruri'],
    createdAt: new Date(lastMonthYear, lastMonth, 5).toISOString(),
  },
  {
    id: 'txn_016',
    type: 'expense',
    amount: 12000,
    categoryId: 'shopping',
    note: 'Amazon Sale - Electronics',
    date: new Date(lastMonthYear, lastMonth, 10).toISOString(),
    tags: ['luxury'],
    createdAt: new Date(lastMonthYear, lastMonth, 10).toISOString(),
  },
  {
    id: 'txn_017',
    type: 'income',
    amount: 15000,
    categoryId: 'freelance',
    note: 'Logo design - StartupXYZ',
    date: new Date(lastMonthYear, lastMonth, 12).toISOString(),
    tags: ['work'],
    createdAt: new Date(lastMonthYear, lastMonth, 12).toISOString(),
  },
  {
    id: 'txn_018',
    type: 'expense',
    amount: 7500,
    categoryId: 'education',
    note: 'Udemy courses + books',
    date: new Date(lastMonthYear, lastMonth, 15).toISOString(),
    tags: ['work'],
    createdAt: new Date(lastMonthYear, lastMonth, 15).toISOString(),
  },
  {
    id: 'txn_019',
    type: 'expense',
    amount: 15000,
    categoryId: 'investment',
    note: 'SIP - Zerodha Mutual Fund',
    date: new Date(lastMonthYear, lastMonth, 16).toISOString(),
    tags: ['fixed'],
    createdAt: new Date(lastMonthYear, lastMonth, 16).toISOString(),
  },
  {
    id: 'txn_020',
    type: 'expense',
    amount: 2800,
    categoryId: 'transport',
    note: 'Petrol + Metro card recharge',
    date: new Date(lastMonthYear, lastMonth, 20).toISOString(),
    tags: ['zaruri'],
    createdAt: new Date(lastMonthYear, lastMonth, 20).toISOString(),
  },
]
